version: "2.3"
services:
  containersettings:
    container_name: testcontainer
    image: testimage
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "0900:0900"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../:/home/dl-box/data/volumes/
    mem_limit: '30gb'
    command: /opt/conda/envs/testimage/bin/jupyter notebook --ip='0.0.0.0' --port=0900 --no-browser --allow-root
